// MongoDB Collection Mappings (replaces PostgreSQL Drizzle schemas)
module.exports = {
  users: { tableName: 'users' },
  categories: { tableName: 'categories' },
  products: { tableName: 'products' },
  paymentMethods: { tableName: 'payment_methods' },
  floors: { tableName: 'floors' },
  tables: { tableName: 'tables' },
  coupons: { tableName: 'coupons' },
  couponUsages: { tableName: 'coupon_usages' },
  promotionUsages: { tableName: 'promotion_usages' },
  promotions: { tableName: 'promotions' },
  customers: { tableName: 'customers' },
  sessions: { tableName: 'sessions' },
  orders: { tableName: 'orders' },
  orderLines: { tableName: 'order_lines' },
  payments: { tableName: 'payments' },
  kdsTickets: { tableName: 'kds_tickets' },
  kdsTicketItems: { tableName: 'kds_ticket_items' },
  selfOrderingSettings: { tableName: 'self_ordering_settings' },
  receipts: { tableName: 'receipts' },
};
